version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  webjee:
    build: ./WEB-JEE
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
