apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort  # ✅ Garde UNE SEULE fois 'type'
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001  # ✅ Entre 30000 et 32767
