apiVersion: v1
kind: Service
metadata:
  name: webjee-service
spec:
  type: NodePort
  selector:
    app: webjee
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30002
