apiVersion: apps/v1
kind: Deployment
metadata:
  name: webjee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webjee
  template:
    metadata:
      labels:
        app: webjee
    spec:
      containers:
      - name: webjee
        image: chaimae17/webjee:latest
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_URL
          value: "http://backend-service:5000"
